# Generated by Django 5.1.2 on 2025-01-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
