# Generated by Django 5.1.2 on 2025-01-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_view_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='private',
        ),
        migrations.AddField(
            model_name='video',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
