# Generated by Django 5.1.2 on 2025-01-06 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sound_video_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.sound'),
        ),
    ]
