# Generated by Django 5.1.2 on 2025-01-07 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_video_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.sound'),
        ),
    ]
