# Generated by Django 5.1.2 on 2025-01-10 05:07

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to=main.utils.file_upload),
        ),
    ]
