# Generated by Django 5.1.2 on 2025-01-10 06:05

import main.models.sound
import main.models.video
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to=main.models.sound.upload_sound),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to=main.models.video.upload_video),
        ),
    ]
